// src/system/coverageMap.js
//
// HASIL AUTO-SCAN dari repo spmbsmpmuslimin/administrasi-smp-muslimin (15 Sep 2026)
// create/read/update/delete dideteksi otomatis lewat pola .from('tabel').insert/select/update/delete
// di seluruh src/**/*.js. Heuristik text-based - kemungkinan ada false positive/negative kecil,
// terutama kalau ada helper/service layer yang manggil beda pola. Tetap worth spot-check.

export const tableCoverage = {
  academic_years: {
    page: "setting/academic/AcademicYearTab.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes:
      "Catatan: page lama 'setting/academic/AcademicYearTab.js' gak ketemu query ke tabel ini di scan; ditemukan malah di: e-raport/CetakRaport.js, pages/attendance/AdminAttendance.js, services/academicYearService.js",
  },
  announcement: {
    page: "components/AnnouncementPopup.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  announcement_reads: {
    page: null,
    create: true,
    read: true,
    update: false,
    delete: false,
    notes:
      "Auto-record: dicatat otomatis saat user baca announcement (found in components/AnnouncementList.js)",
  },
  app_config: {
    page: "setting/MaintenanceModeTab.js",
    create: false,
    read: true,
    update: true,
    delete: false,
    notes:
      "Catatan: page lama 'setting/MaintenanceModeTab.js' gak ketemu query ke tabel ini di scan; ditemukan malah di: setting/AdminPanel.js",
  },
  attendance_eraport: {
    page: "e-raport/InputKehadiran.js",
    create: false,
    read: false,
    update: false,
    delete: false,
    notes:
      "HASIL SCAN: tabel ini TIDAK dipakai di file manapun (termasuk InputKehadiran.js yang dipetakan di sini — file itu ternyata query catatan_eraport, bukan attendance_eraport). Perlu dicek manual.",
  },
  attendances: {
    page: "pages/attendance/Attendance.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  catatan_eraport: {
    page: "e-raport/InputCatatan.js",
    create: true,
    read: true,
    update: true,
    delete: false,
    notes: "",
  },
  classes: {
    page: "pages/Classes.js",
    create: true,
    read: true,
    update: false,
    delete: false,
    notes: "",
  },
  cleanup_history: {
    page: "system/DatabaseCleanupMonitor.js",
    create: true,
    read: true,
    update: false,
    delete: false,
    notes: "Auto-generate dari sistem cleanup",
  },
  ekstrakurikuler_eraport: {
    page: "e-raport/InputEkstrakurikuler.js",
    create: false,
    read: true,
    update: false,
    delete: false,
    notes:
      "Catatan: page lama 'e-raport/InputEkstrakurikuler.js' gak ketemu query ke tabel ini di scan; ditemukan malah di: e-raport/CetakRaport.js",
  },
  eraport_settings: {
    page: null,
    create: false,
    read: true,
    update: true,
    delete: false,
    notes: "",
  },
  feedback_guru: {
    page: "components/FeedbackGuru.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  grades: {
    page: "pages/grades/Grades.js",
    create: true,
    read: true,
    update: false,
    delete: true,
    notes: "Fix: path lama typo 'pages/grade/' (singular), folder asli 'pages/grades/' (plural)",
  },
  grades_katrol: {
    page: "pages/grades/GradesKatrol.js",
    create: true,
    read: true,
    update: false,
    delete: true,
    notes: "Fix: path lama typo 'pages/grade/' (singular), folder asli 'pages/grades/' (plural)",
  },
  grades_katrol_settings: {
    page: null,
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  jurnal_harian: {
    page: null,
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  konseling: {
    page: "konseling/Konseling.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  nilai_eraport: {
    page: "e-raport/InputNilai.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  nilai_eraport_detail: {
    page: "e-raport/InputTP.js",
    create: true,
    read: false,
    update: true,
    delete: true,
    notes:
      "Catatan: page lama 'e-raport/InputTP.js' gak ketemu query ke tabel ini di scan; ditemukan malah di: e-raport/CetakRaport.js, e-raport/InputNilai.js",
  },
  raport_config: {
    page: "e-raport/RaportConfig.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  raport_metadata: {
    page: null,
    create: true,
    read: true,
    update: true,
    delete: false,
    notes: "",
  },
  school_settings: {
    page: "setting/SchoolSettingsTab.js",
    create: true,
    read: true,
    update: true,
    delete: false,
    notes:
      "Catatan: page lama 'setting/SchoolSettingsTab.js' gak ketemu query ke tabel ini di scan; ditemukan malah di: App.js, components/Logo.js, e-raport/CetakRaport.js",
  },
  siswa_baru: {
    page: "spmb/StudentList.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes:
      "Catatan: page lama 'spmb/StudentList.js' gak ketemu query ke tabel ini di scan; ditemukan malah di: services/academicYearService.js, setting/academic/YearTransition.js, setting/school-management/SchoolManagementTab.js",
  },
  spmb_settings: {
    page: "spmb/SPMB.js",
    create: false,
    read: true,
    update: false,
    delete: false,
    notes: "",
  },
  student_development_notes: {
    page: "pages/CatatanSiswa.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  students: {
    page: "pages/Students.js",
    create: true,
    read: true,
    update: true,
    delete: false,
    notes: "",
  },
  system_health_logs: {
    page: "system/MonitorHistory.js",
    create: true,
    read: true,
    update: false,
    delete: true,
    notes:
      "Auto-generate dari HealthChecker (found in system/HealthChecker.js & MonitorDashboard.js, bukan cuma MonitorHistory.js)",
  },
  teacher_assignments: {
    page: "setting/TeacherAssignmentTab.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes:
      "Catatan: page lama 'setting/TeacherAssignmentTab.js' gak ketemu query ke tabel ini di scan; ditemukan malah di: components/AdminJurnalRekap.js, components/HomeroomTeacherDashboard.js, components/TeacherDashboard.js",
  },
  teacher_attendance: {
    page: "attendance-teacher/TeacherAttendance.js",
    create: true,
    read: true,
    update: true,
    delete: false,
    notes: "",
  },
  teacher_schedules: {
    page: "pages/TeacherSchedule.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  tujuan_pembelajaran: {
    page: "e-raport/InputTP.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
  users: {
    page: "setting/UserManagementTab.js",
    create: true,
    read: true,
    update: true,
    delete: true,
    notes: "",
  },
};
